---
- hosts: proxybox
  gather_facts: false
  tasks:
    - name: fetch cert from proxybox onto local machine
      fetch:
        src: /tmp/root
        dest: /tmp/local_mitm.crt
        flat: true

- hosts: localhost
  gather_facts: false
  tasks:
    - shell: ls -al /tmp/local_mitm.crt

- hosts: localbox
  vars:
    cert_dir: "/usr/local/share/ca-certificates/wire.com"
  tasks:
    - name: create man-in-the-middle certificate directory
      file:
        path: "{{ cert_dir }}"
        state: directory
        mode: 0755
    - name: copy certificate
      copy:
        src: "/tmp/local_mitm.crt"
        dest: "{{ cert_dir }}/local_mitm.crt"
        mode: 0644
