# Used to maintain compatibility 1.9 - 2.3 for servers with both initd and systemd
#
# See https://github.com/ansible/ansible/issues/19422
# contrary to bug description, `use: service` to force 'service' instead of 'systemctl' in 2.2/2.3 works.
#
# if used with the service module `use` keyword, prevents issues of the type
#  `FAILED! => "Error loading unit file 'collectd': org.freedesktop.DBus.Error.FileNotFound`
# in ansible 2.2/2.3 while remaining compatible with ansible 1.9-2.1
#
# Use this module by
#
# 1. Adding `role: service_module_compat` to meta/dependencies
# 2. Adding `use: '{{ service_manager | default(omit) }}'
# e.g.
#
#- service:
#    name: ntp
#    state: started
#    use: '{{ service_manager | default(omit) }}'

- name: set ansible_version2.2 fact
  set_fact:
    service_manager: 'service'
  when: ansible_version.full | version_compare('2.2', operator='gt', strict=False)
