---
- name: ensure offline_delivery_dir is set
  set_fact: offline_delivery_dir='/home/ubuntu/offline_delivery/'
  when: offline_delivery_dir is undefined

- name: ensure fake_domain is given.
  fail:
    msg: 'fake_domain must be set'
  when: fake_domain is undefined

- name: ensure ansnode_ip is given.
  fail:
    msg: 'ansnode_ip must be set'
  when: ansnode_ip is undefined

- name: ensure node_number is given.
  fail:
    msg: 'node_number must be set'
  when: node_number is undefined

- name: ensure dnsmasq directory exists
  file:
    path: '{{ offline_delivery_dir }}/dnsmasq/dnsmasq.d/'
    state: directory
  become: yes

- name: add DNS entry for ansnode{{ node_number }}
  copy:
    content: |
      address=/ip-{{ ansnode_ip | replace('.','-')}}.{{ fake_domain }}/{{ ansnode_ip }}
    dest: '{{ offline_delivery_dir }}/dnsmasq/dnsmasq.d/ansnode{{ node_number }}'

#      address=/etcd0{{ node_number }}.{{ fake_domain }}/{{ ansnode_ip }}
#      address=/ansnode0{{ node_number }}.{{ fake_domain }}/{{ ansnode_ip }}
- name: restart DNSMASQ
  systemd:
    name: dnsmasq
    state: restarted
    daemon_reload: yes
  become: yes


