- name: Include Prompts
  hosts: localhost
  gather_facts: no
  become: no
  tasks:
    - name: prompt for what infrastructure we're using.
      import_tasks: prompts/vpc-or-kvm.yml
      when: wdt_infra == 'prompt'
    - name: prompt for what region we're deploying to.
      import_tasks: prompts/region.yml
      when: wdt_region == 'prompt' and wdt_infra == 'vpc' 
    - name: prompt for what environment we're deploying to.
      import_tasks: prompts/environment.yml
      when: wdt_env == 'prompt'
    - name: prompt for the target IP.
      import_tasks: prompts/first_target.yml
      vars:
        label: the target bastion host

- name: Golden image
  hosts: first_target_host
  gather_facts: no
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Golden image remote target
      import_tasks: golden_image-tasks.yml
      when: wdt_type != "khan"

- name: Golden image
  hosts: '{{ wdt_dns }}'
  vars_files:
    - group_vars/all
  gather_facts: no
  remote_user: ubuntu
  pre_tasks:
    - meta: end_play
      when: ('dummy' in play_hosts)
  tasks:
    - name: Golden image remote target
      import_tasks: golden_image-tasks.yml
      when: wdt_type == "khan"
