---
- name: update apt cache
  apt: >
    update_cache=yes
    cache_valid_time={{ package_apt_cache_time }}

- name: add apt_repository dependencies
  apt: >
    pkg=python-pycurl
    force=yes
    state=present
  when: "package_repo != ''"

- name: add {{ package_name }} repository
  apt_repository: >
    repo='{{ package_repo }}'
    state=present
  when: "package_repo != ''"

- name: install latest {{ package_name }} package
  apt: >
    pkg={{ package_name }}
    force=yes
    state=latest
  when: "package_version == 'latest'"

- name: install {{ package_name }}={{ package_version }} package
  apt: >
    pkg='{{ package_name }}={{ package_version }}'
    force=yes
    state=present
  when: "package_version != 'latest'"
