- name: hard code vpn server primary interface
  set_fact:
    vpn_server_primary_if: 'eth0'
  when: wdt_infra == 'aws'
  tags: iptables

- name: detect vpn server primary interface
  command: ' bash -c "ip route | grep default | grep 172 | sed \"s/.*dev \(.*\) proto.*/\1/\""'
  register: kvm_172_if
  when: wdt_infra == 'kvm'
  tags: iptables

- name: select vpn server name (kvm)
  set_fact:
    vpn_server_primary_if: '{{ kvm_172_if.stdout }}'
  when: wdt_infra == 'kvm'
  tags: iptables

- name: configure iptables, overwriting default config
  template: >
    src=rules.v4.j2
    dest=/etc/iptables/rules.v4
    owner=root
    group=root
    mode=400
  notify:
    - start iptables-persistent
  tags: iptables
