
### Define the following variables when using this role

## Should be set by inventory/group_vars according to region.
#vpn_routing:
#  primary:   ~
#  secondary: ~
#  ccd:       {}
  # dhcp:
    # server: []
    # route:  []
    # push:   []

###

vpn_home_dir:    /etc/openvpn/server
vpn_ca_dir:      '{{ vpn_home_dir }}/ca'
vpn_ccd_dir:     '{{ vpn_home_dir }}/ccd'
vpn_domain:      '{{ env_domain }}'
vpn_certs_dir:   '{{ vpn_ca_dir }}/clientcerts'
vpn_script_dir:  '{{ vpn_home_dir }}/script'
vpn_server_name: '{{ wdt_region_abbrev }}-{{ vpn_server_ord }}.{{ vpn_domain }}'
vpn_primary_server_name:   '{{ wdt_region_abbrev }}-{{ vpn_primary_name }}.{{ vpn_domain }}'
vpn_secondary_server_name: '{{ wdt_region_abbrev }}-{{ vpn_secondary_name }}.{{ vpn_domain }}'

# Files to sync / backup from primary to secondary
vpn_sync_files:
  - index.txt
  - index.txt.attr
  - index.txt.attr.old
  - index.txt.old
  - serial
  - serial.old
  - crlnumber
  - crlnumber.old

# Directories to sync / backup from primary to secondary
vpn_sync_dirs:
  - newcerts
  - certs
  - crl
