---
- name: ensure rsyslogd package is installed
  apt: pkg=rsyslog state=present

- name: replace rsyslog.conf
  copy: >
    src=rsyslog.conf
    dest=/etc/rsyslog.conf
    owner=root
    group=root
    mode=0644

- name: prune /etc/rsyslog.d
  file: >
    path=/etc/rsyslog.d
    state=absent

- name: re-create /etc/rsyslog.d
  file: >
    path=/etc/rsyslog.d
    owner=root
    group=root
    mode=0755
    state=directory

- name: default config
  copy: >
    src=50-default.conf
    dest=/etc/rsyslog.d/50-default.conf
    owner=root
    group=root
    mode=0644

- name: render remote forwarding config
  template: >
    src=10-remote.conf.j2
    dest=/etc/rsyslog.d/10-remote.conf
    owner=root
    group=root
    mode=0644
  notify: reload rsyslogd
